name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: scraped2rss

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write  # Necessary for signing with cosign

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Install cosign for signing the Docker image
        uses: sigstore/cosign-installer@v3.3.0

      - name: Sign the Docker image with cosign
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: |
          cosign sign ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify the Docker image signature
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: |
          cosign verify ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
