name: Build and Publish Docker Image

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
env:
  IMAGE_NAME: scraped2rss

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}  # Uses the GITHUB_TOKEN secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/IMAGE_NAME:latest  # Replace IMAGE_NAME with your image's name

